name: "Nim documentation generator"
description: "Automatically builds documentation with a few extra niceties that I like"
inputs:
  main-file:
    description: "Main Nim file which to build documentation with (relative to root of `project-dir`)"
    required: true

  out-dir:
    description: "Where to put the files (Relative to `project-dir`"
    required: true
    default: "site/"

  project-dir:
    description: "Folder containing the .nimble file"
    required: true
    default: "./"

runs:
  using: composite
  steps:
    # Convert all the nimble variables into ENV variables for easy access
    - name: "Convert nimble files to ENV variables"
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      run: |
        nimble dump | sed -E "s/(\w+): \"(.*)\"/nimble_\\1=\\2/" >> $GITHUB_ENV

    # To remove the src/ prefix in the pages we add a dummy
    # .nimble file so that Nim thinks the files are root level
    - name: "Create dummy nimble file"
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      run: touch "$nimble_srcDir/dummy.nimble"

    - name: "Run doc generation"
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      run: >
        nimble doc  --project --outdir=${{ inputs.out-dir }} --index:on --git.url:$GITHUB_SERVER_URL/$GITHUB_REPOSITORY --git.commit:$GITHUB_SHA ${{ inputs.main-file }}


