name: "Nim documentation generator"
description: "Automatically builds documentation with a few extra niceties that I like"
author: "Jake Leahy"
branding:
  icon: book
  color: yellow
inputs:
  main-file:
    description: "Main Nim file which to build documentation with (relative to root of `project-dir`)"
    required: true

  out-dir:
    description: "Where to put the files (Relative to `project-dir`)"
    required: true
    default: "site/"

  project-dir:
    description: "Folder containing the .nimble file"
    required: true
    default: "./"

  build-index:
    description: "Whether to build indexes first or not (Can be disabled if you don't use importdoc)"
    required: true
    default: "true" # We don't get booleans?

  deploy:
    description: "Automatically deploy the site. Currently only supports Github pages"
    required: false
    default: "none"

  devel-branch:
    description: "Development branch to link to in the `edit` button. Defaults to the default branch in git"
    required: false
    default: ""

  extra-files:
    description: "Extra documentation files to render. Can either be markdown or Nim files"
    required: false
    default: ""

outputs:
  site-dir:
    description: "Path to built documentation"
    value: ${{ inputs.project-dir }}/${{ inputs.out-dir }}

runs:
  using: composite
  steps:
    - name: "Run doc generation"
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      run: ${GITHUB_ACTION_PATH}/scripts/buildDocs.sh "HEAD" "${{ inputs.project-dir }}" "${{ inputs.main-file }}" "${{ inputs.devel-branch }}" "${{ inputs.build-index }}" "${{ inputs.extra-files }}" "${{ inputs.out-dir }}"

    #
    # Github pages deployment
    #

    - name: "Create artefact"
      if: ${{ inputs.deploy == 'pages' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.project-dir }}/${{ inputs.out-dir }}

    - name: "Deploy to pages"
      if: ${{ inputs.deploy == 'pages' }}
      uses: actions/deploy-pages@v4
