name: "Nim documentation generator"
description: "Automatically builds documentation with a few extra niceties that I like"
author: "Jake Leahy"
branding:
  icon: book
  color: yellow
inputs:
  main-file:
    description: "Main Nim file which to build documentation with (relative to root of `project-dir`)"
    required: true

  out-dir:
    description: "Where to put the files (Relative to `project-dir`)"
    required: true
    default: "site/"

  project-dir:
    description: "Folder containing the .nimble file"
    required: true
    default: "./"

  build-index:
    description: "Whether to build indexes first or not (Can be disabled if you don't use importdoc)"
    required: true
    default: "true" # We don't get booleans?

  deploy:
    description: "Automatically deploy the site. Currently only supports Github pages"
    required: false
    default: "none"

  devel-branch:
    description: "Development branch to link to in the `edit` button. Defaults to the default branch in git"
    required: false
    default: ""

  extra-files:
    description: "Extra documentation files to render. Can either be markdown or Nim files"
    required: false
    default: ""

  versions:
    description: "Space separated list of versions to build documentation for. `HEAD` builds latest commit and `stable` builds latest published version"
    required: false
    default: stable

outputs:
  site-dir:
    description: "Path to built documentation"
    value: ${{ inputs.project-dir }}/${{ inputs.out-dir }}

runs:
  using: composite
  steps:
    - name: "Run doc generation"
      shell: bash
      run: |
        set -e
        for version in ${{ inputs.versions }}; do
          ${GITHUB_ACTION_PATH}/scripts/buildDocs.sh "$version" "${{ inputs.project-dir }}" "${{ inputs.main-file }}" "${{ inputs.devel-branch }}" "${{ inputs.build-index }}" "${{ inputs.extra-files }}" "${{ inputs.out-dir }}"
          source <($(cd ${{ inputs.project-dir }} && $GITHUB_ACTION_PATH/scripts/nimbleVar.sh))
          case "${version}" in
            stable)
              echo " - [$nimble_version (latest)](stable)" >> versions.md ;;
            HEAD)
              echo " - [Latest commit](develop)" >> versions.md ;;
            *)
              echo " - [$version]($version)" >> versions.md ;;
          esac
        done

    - name: "Generate index for all the versions"
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      run: nim md2html --out:"${{ inputs.out-dir }}/index.html" ${GITHUB_ACTION_PATH}/versions.md

    #
    # Github pages deployment
    #

    - name: "Create artefact"
      if: ${{ inputs.deploy == 'pages' }}
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ inputs.project-dir }}/${{ inputs.out-dir }}

    - name: "Deploy to pages"
      if: ${{ inputs.deploy == 'pages' }}
      uses: actions/deploy-pages@v4
